# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{spatial_adapter}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Pete Deffendol}, %q{Guilhem Vellut}]
  s.date = %q{2011-08-15}
  s.description = %q{Provides enhancements to ActiveRecord to handle spatial datatypes in PostgreSQL and MySQL.}
  s.email = %q{pete@fragility.us}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "VERSION",
    "lib/spatial_adapter.rb",
    "lib/spatial_adapter/connection_adapters/abstract/index_definition.rb",
    "lib/spatial_adapter/connection_adapters/abstract/table_definition.rb",
    "lib/spatial_adapter/connection_adapters/mysql/spatial_mysql_column.rb",
    "lib/spatial_adapter/connection_adapters/mysql2/spatial_mysql2_column.rb",
    "lib/spatial_adapter/connection_adapters/mysql2_adapter.rb",
    "lib/spatial_adapter/connection_adapters/mysql_adapter.rb",
    "lib/spatial_adapter/connection_adapters/postgresql/postgresql_column_definition.rb",
    "lib/spatial_adapter/connection_adapters/postgresql/postgresql_table_definition.rb",
    "lib/spatial_adapter/connection_adapters/postgresql/spatial_postgresql_column.rb",
    "lib/spatial_adapter/connection_adapters/postgresql_adapter.rb",
    "lib/spatial_adapter/railtie.rb",
    "lib/spatial_adapter/raw_geom_info.rb",
    "lib/spatial_adapter/schema_dumper.rb",
    "lib/spatial_adapter/spatial_column.rb",
    "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/fragility/spatial_adapter}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Spatial Adapter for ActiveRecord}
  s.test_files = [%q{spec/db/mysql2_raw.rb}, %q{spec/db/mysql_raw.rb}, %q{spec/db/postgis_raw.rb}, %q{spec/models/common.rb}, %q{spec/mysql/connection_adapter_spec.rb}, %q{spec/mysql/migration_spec.rb}, %q{spec/mysql/models_spec.rb}, %q{spec/mysql/schema_dumper_spec.rb}, %q{spec/mysql2/connection_adapter_spec.rb}, %q{spec/mysql2/migration_spec.rb}, %q{spec/mysql2/models_spec.rb}, %q{spec/mysql2/schema_dumper_spec.rb}, %q{spec/postgresql/connection_adapter_spec.rb}, %q{spec/postgresql/migration_spec.rb}, %q{spec/postgresql/models_spec.rb}, %q{spec/postgresql/schema_dumper_spec.rb}, %q{spec/shared_examples.rb}, %q{spec/spec_helper.rb}, %q{spec/README.txt}]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.2.2"])
      s.add_runtime_dependency(%q<GeoRuby>, [">= 1.3.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.2.2"])
      s.add_dependency(%q<GeoRuby>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.2.2"])
    s.add_dependency(%q<GeoRuby>, [">= 1.3.0"])
  end
end

